spring:
  application:
    name: accomodation_marketplace

  datasource:
    url: jdbc:mysql://localhost:3306/accomodation_marketplace?useSSL=false&serverTimezone=UTC
    username: root
    password: Krutika@24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8081